# Uncomment the next line to define a global platform for your project

source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

def libs_pods
  pod 'SQLite.swift', '~> 0.12.2'
  pod 'Then', '~> 2.7.0'
  pod 'SwiftDate', '~> 6.3.1'
  pod 'SBLibrary'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'ObjectMapper', '~> 4.2.0'
end

def tools_pods
  pod 'CocoaLumberjack/Swift', '~> 3.7.0'
end

target 'SQLiteSwiftExample' do

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  libs_pods
  tools_pods
  
  # Pods for SQLiteSwiftExample

end
